version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_vector_db
    ports:
      - "127.0.0.1:6333:6333"
      # - "6333:6333"
    volumes:
      - ./appqdrant_storage:/qdrant/storage
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "127.0.0.1:6379:6379"
    restart: always

  postgres:
    image: postgres:18.4
    container_name: postgres_ai
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    restart: always

  app:
    build: .
    container_name: ta_park_ai_app
    env_file:
      - .env
    ports:
      - "127.0.0.1:8881:8881"
    depends_on:
      - qdrant
      - redis
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    volumes:
      - ./app/support_ai/resources/RAG/knowledge_base:/app/app/support_ai/resources/RAG/knowledge_base
      # - /containers/src/vehicle/TaPark/logs:/logs
    restart: always

networks:
  default:
    external: true
    name: tapark_default