version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_vector_db
    ports:
      - "6333:6333"
    volumes:
      - ./appqdrant_storage:/qdrant/storage
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --requirepass MyStrongPassword123
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    container_name: ta_park_ai_app
    env_file:
      - .env
    ports:
      - "8881:8881"
    depends_on:
      - qdrant
      - redis
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    restart: always